### PR TITLE
Defer most argument processing to kubectl set image

### PR DESCRIPTION
**Pull request by aelkiss**
- set image *does* support cronjobs

- it also supports updating multiple resources, types of resources, and
  multiple containers

### CODE REVIEW

**Comment by aelkiss** [comment]
I suggest releasing this as the action v3. 

Note that you can try out `kubectl set image` directly without actually changing anything with `kubectl set image --dry-run=client ...`

**Comment by aelkiss** [comment]
After removing the stray ';;', I was able to use this branch of the action to deploy to production with https://github.com/hathitrust/datasets/runs/8214497533?check_suite_focus=true

**Comment by aelkiss** [comment]
README needs to be updated

**Review by niquerio — COMMENTED** [review]
Wondering about the inputs `type` and `resource`. Maybe they should be `resource_type` and `resource_name`. Also, should the default container be * instead of `web`?

**Comment by aelkiss** [comment]
Yes, I think `resource_type` and `resource_name` better match how kubectl describes those arguments.

I would hesitate to set default container to `*` -- while that would work in cases where there's only a single container in the pod regardless of what it's named, it's guaranteed to break things when there are multiple containers. By default, it will set the image for the container 'web' in deployment 'web', which is generally the current default. I suppose we could default the container name to be the same as the resource name -- that would be less likely to break stuff unexpectedly than '*' - or maybe there's a way to require that if we pass the resource name we also have to pass a container name?

**Comment by niquerio** [comment]
@aelkiss I updated the names to `resource_type` and `resource_name`; can you check that it still works?

**Comment by aelkiss** [comment]
I updated the parameter names & re-ran the action using the same release -- looks fine:

https://github.com/hathitrust/datasets/actions/runs/3083264707/jobs/4983982381

**Pull request merged**
